import {createAdaptiveStyles} from '../theme';
import React, {useMemo} from 'react';
import {ScrollView, StyleSheet, Text, View} from 'react-native';

export type ActivityDay={date:string;total:number;interviewUnderstood?:number;codingSolved?:number};
export function ActivityHeatmap({days}:{days:ActivityDay[]}):React.JSX.Element{
 const weeks=useMemo(()=>{const today=new Date();today.setUTCHours(0,0,0,0);const sunday=new Date(today);sunday.setUTCDate(sunday.getUTCDate()-sunday.getUTCDay()-52*7);const counts=new Map(days.map(day=>[day.date,day.total]));return Array.from({length:53},(_week,week)=>{const start=new Date(sunday);start.setUTCDate(start.getUTCDate()+week*7);const month=start.toLocaleString(undefined,{month:'short',timeZone:'UTC'});const prev=week?new Date(sunday):null;if(prev)prev.setUTCDate(prev.getUTCDate()+(week-1)*7);const label=!prev||prev.getUTCMonth()!==start.getUTCMonth()?month:'';return{label,cells:Array.from({length:7},(_day,dayIndex)=>{const date=new Date(start);date.setUTCDate(date.getUTCDate()+dayIndex);const key=date.toISOString().slice(0,10);return{key,count:counts.get(key)||0}})}})},[days]);
 const maximum=Math.max(1,...days.map(day=>day.total));
 const tint=(count:number)=>count===0?'#edf0f6':count/maximum>=.75?'#176b43':count/maximum>=.45?'#2e9b62':count/maximum>=.2?'#70c895':'#b8e5ca';
 const legendStyles=[styles.legendZero,styles.legendOne,styles.legendTwo,styles.legendThree,styles.legendFour];
 return <View><View style={styles.gridFrame}><View style={styles.weekdayLabels} accessible accessibilityLabel="Weekday columns: Sunday through Saturday"><Text style={styles.weekday}>S</Text><Text style={styles.weekday}/><Text style={styles.weekday}>T</Text><Text style={styles.weekday}/><Text style={styles.weekday}>F</Text><Text style={styles.weekday}/><Text style={styles.weekday}/></View><ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={styles.grid} accessibilityLabel="Practice activity by day; swipe horizontally to review the year">{weeks.map((week,index)=><View key={index} style={styles.weekColumn}><Text style={styles.month}>{week.label}</Text><View style={styles.week}>{week.cells.map(cell=><View key={cell.key} accessible accessibilityRole="text" accessibilityLabel={`${cell.key}: ${cell.count} practice ${cell.count === 1 ? 'completion' : 'completions'}`} style={[styles.cell,{backgroundColor:tint(cell.count)}]}/>)}</View></View>)}</ScrollView></View><View style={styles.legend} accessibilityLabel="Activity legend: less activity to more activity"><Text style={styles.legendText}>Less</Text>{legendStyles.map((levelStyle,level)=><View key={level} style={[styles.legendCell,levelStyle]}/>)}<Text style={styles.legendText}>More</Text></View></View>;
}
const styles=createAdaptiveStyles(StyleSheet.create({month:{position:'absolute',top:0,left:0,width:34,height:17,color:'#737b8c',fontSize:7,fontWeight:'700'},gridFrame:{flexDirection:'row',alignItems:'center'},weekdayLabels:{width:20,height:106,justifyContent:'space-between',paddingTop:20,paddingBottom:2},weekday:{height:11,color:'#737b8c',fontSize:7,lineHeight:10},grid:{gap:3,paddingVertical:3,paddingRight:6},weekColumn:{position:'relative',gap:1,paddingTop:18},week:{gap:3},cell:{width:10,height:10,borderRadius:3},legend:{flexDirection:'row',alignItems:'center',justifyContent:'flex-end',gap:4,marginTop:8},legendText:{color:'#737b8c',fontSize:8},legendCell:{width:10,height:10,borderRadius:3},legendZero:{backgroundColor:'#edf0f6'},legendOne:{backgroundColor:'#b8e5ca'},legendTwo:{backgroundColor:'#70c895'},legendThree:{backgroundColor:'#2e9b62'},legendFour:{backgroundColor:'#176b43'}}));
