import React, {useCallback, useState} from 'react';
import {ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {adminApi, communityApi, getApiErrorMessage} from '../services/api';
import {useAuth} from '../context/AuthContext';
import {AdminUser, AdminUsersPanel} from './AdminUsersPanel';

type Tab='Overview'|'Users'|'Subjects'|'Review'|'Reports';
type Subject={_id:string;name:string;courseCode?:string;track?:string;branch?:string;semester?:number};
type Report={_id:string;resourceTitle:string;resourceUrl:string;resourceType:string;topic?:string;subject?:{name?:string};status:string};
type ReviewNote={_id:string;title:string;description?:string;unitTitle?:string;originalName?:string;subject?:{name?:string};contributor?:{name?:string;email?:string};bounty?:{title?:string;reward?:number}};
export function AdminConsoleScreen():React.JSX.Element{
 const{logout}=useAuth();const[tab,setTab]=useState<Tab>('Overview');const[stats,setStats]=useState<{totalUsers:number;totalSubjects:number;totalTenants:number}|null>(null);const[subjects,setSubjects]=useState<Subject[]>([]);const[reports,setReports]=useState<Report[]>([]);const[review,setReview]=useState<ReviewNote[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[subjectEditor,setSubjectEditor]=useState<{id?:string;json:string}|null>(null);
 const load=useCallback(async(background=false)=>{background?setRefreshing(true):setLoading(true);setError('');const results=await Promise.allSettled([adminApi.overview(),adminApi.subjects(),adminApi.reports(),communityApi.moderationQueue()]);let failures=0;const read=<T,>(index:number,apply:(value:T)=>void)=>{const item=results[index];if(item.status==='fulfilled')apply(item.value.data as T);else failures++;};read<{stats?:typeof stats}>(0,v=>setStats(v.stats||null));read<{subjects?:Subject[]}>(1,v=>setSubjects(v.subjects||[]));read<{reports?:Report[]}>(2,v=>setReports(v.reports||[]));read<{notes?:ReviewNote[]}>(3,v=>setReview(v.notes||[]));if(failures)setError(failures===4?'Admin data is unavailable. Confirm this account has administrator access.':'Some admin panels could not refresh. Pull to retry.');setLoading(false);setRefreshing(false);},[]);
 useFocusEffect(useCallback(()=>{load(true).catch(e=>setError(getApiErrorMessage(e,'Could not load the admin console.')));},[load]));
 const resolveReport=async(item:Report,status:'RESOLVED'|'DISMISSED')=>{setBusy(item._id);try{await adminApi.updateReport(item._id,status);setReports(list=>list.filter(report=>report._id!==item._id));}catch(e){Alert.alert('Report not updated',getApiErrorMessage(e,'Please retry.'));}finally{setBusy('');}};
 const reviewNote=async(item:ReviewNote,decision:'APPROVE'|'REJECT')=>{setBusy(item._id);try{await communityApi.reviewNote(item._id,{decision,reviewNote:decision==='APPROVE'?'Approved from mobile admin console.':'Rejected from mobile admin console.'});setReview(list=>list.filter(note=>note._id!==item._id));Alert.alert('Review saved',decision==='APPROVE'?'The note was approved and contributor credits were handled by the server.':'The note was rejected.');}catch(e){Alert.alert('Review not saved',getApiErrorMessage(e,'Refresh the queue and try again.'));}finally{setBusy('');}};
 const deleteUser=(item:AdminUser,onDeleted:()=>void)=>Alert.alert('Delete user account?',`This permanently removes ${item.name}'s account and related progress data.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>{setBusy(item._id);adminApi.deleteUser(item._id).then(()=>{setStats(current=>current?{...current,totalUsers:Math.max(0,current.totalUsers-1)}:current);onDeleted();}).catch(e=>Alert.alert('Account not deleted',getApiErrorMessage(e,'Resolve active bounties first.'))).finally(()=>setBusy(''));}}]);
 const newSubject=()=>{setSubjectEditor({json:JSON.stringify({name:'',courseCode:'',track:'UNIVERSITY',tenantId:'',branch:'CSE',semester:1,credits:3,units:[],careerBridge:{}},null,2)});setError('')};
 const editSubject=async(item:Subject)=>{setBusy(item._id);try{const response=await adminApi.subject(item._id);const subject=(response.data as {subject?:Record<string,unknown>}).subject;if(!subject)throw new Error('Subject data was missing from the server response.');setSubjectEditor({id:item._id,json:JSON.stringify(subject,null,2)});setError('')}catch(e){Alert.alert('Subject could not load',getApiErrorMessage(e,'Refresh the subject list and retry.'))}finally{setBusy('')}};
 const saveSubject=async()=>{if(!subjectEditor)return;let payload:Record<string,unknown>;try{payload=JSON.parse(subjectEditor.json) as Record<string,unknown>;if(!payload||Array.isArray(payload)||typeof payload!=='object')throw new Error('The subject data must be a JSON object.')}catch(e){Alert.alert('Invalid subject JSON',e instanceof Error?e.message:'Correct the JSON syntax and try again.');return}const tenant=payload.tenant;if(tenant&&typeof tenant==='object'&&'_id'in tenant){payload.tenantId=(tenant as {_id:string})._id;delete payload.tenant}for(const key of ['_id','__v','createdAt','updatedAt'])delete payload[key];setBusy('subject-save');try{if(subjectEditor.id)await adminApi.updateSubject(subjectEditor.id,payload);else await adminApi.createSubject(payload);setSubjectEditor(null);await load(true);Alert.alert('Subject saved','The subject and its related syllabus resources have been saved.')}catch(e){Alert.alert('Subject not saved',getApiErrorMessage(e,'Check required subject fields and your admin access.'))}finally{setBusy('')}};
 const deleteSubject=(item:Subject)=>Alert.alert('Delete subject?',`This removes ${item.name} and its associated progress records.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>{setBusy(item._id);adminApi.deleteSubject(item._id).then(()=>{setSubjects(list=>list.filter(subject=>subject._id!==item._id));setStats(current=>current?{...current,totalSubjects:Math.max(0,current.totalSubjects-1)}:current)}).catch(e=>Alert.alert('Subject not deleted',getApiErrorMessage(e,'Resolve related data and retry.'))).finally(()=>setBusy(''));}}]);
 if(loading)return<View style={styles.center} accessibilityRole="progressbar"><ActivityIndicator size="large" color="#315cf5"/><Text style={styles.muted}>Loading admin workspace…</Text></View>;
 return <View style={styles.screen}><View style={styles.header}><View style={styles.headerRow}><View style={styles.flex}><Text style={styles.eyebrow}>THE ACADEMIA</Text><Text style={styles.title}>Admin console</Text></View><Pressable accessibilityRole="button" onPress={()=>logout()}><Text style={styles.logout}>Sign out</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{(['Overview','Users','Subjects','Review','Reports'] as Tab[]).map(value=><Pressable key={value} accessibilityRole="tab" accessibilityState={{selected:tab===value}} onPress={()=>setTab(value)} style={[styles.tab,tab===value&&styles.activeTab]}><Text style={[styles.tabText,tab===value&&styles.activeTabText]}>{value}</Text></Pressable>)}</ScrollView></View>
 <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor="#315cf5"/>}>{error?<View style={styles.errorCard}><Text style={styles.errorText}>{error}</Text><Pressable onPress={()=>load()}><Text style={styles.action}>Retry</Text></Pressable></View>:null}
 {tab==='Overview'&&<><Text style={styles.section}>Platform overview</Text><View style={styles.stats}>{[['Users',stats?.totalUsers],['Subjects',stats?.totalSubjects],['Campuses',stats?.totalTenants]].map(([label,value])=><View key={String(label)} style={styles.stat}><Text style={styles.statValue}>{value??'—'}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View><Text style={styles.section}>Needs attention</Text><View style={styles.card}><Text style={styles.cardTitle}>{review.length} pending contribution reviews</Text><Pressable onPress={()=>setTab('Review')}><Text style={styles.action}>Review contributions ›</Text></Pressable></View><View style={styles.card}><Text style={styles.cardTitle}>{reports.length} open link reports</Text><Pressable onPress={()=>setTab('Reports')}><Text style={styles.action}>Review reports ›</Text></Pressable></View><Text style={styles.muted}>Subject editing is available through the admin web console; this mobile workspace provides safe review and directory actions.</Text></>}
 {tab==='Users'&&<AdminUsersPanel deletingUserId={busy} onDelete={deleteUser}/>}
 {tab==='Subjects'&&<>{subjectEditor?<View style={styles.card}><View style={styles.headerRow}><Text style={styles.cardTitle}>{subjectEditor.id?'Edit subject':'Create subject'}</Text><Pressable accessibilityRole="button" onPress={()=>setSubjectEditor(null)}><Text style={styles.action}>Close</Text></Pressable></View><Text style={styles.muted}>Edit the complete subject payload as JSON. The server validates track, tenant, syllabus, Exam Night, and Career Bridge fields before saving. For university subjects, tenantId must be a valid university tenant ID.</Text><TextInput accessibilityLabel="Subject data JSON" value={subjectEditor.json} onChangeText={json=>setSubjectEditor(current=>current?{...current,json}:current)} multiline autoCapitalize="none" autoCorrect={false} spellCheck={false} textAlignVertical="top" style={styles.jsonInput}/><Pressable accessibilityRole="button" disabled={busy==='subject-save'} onPress={saveSubject} style={styles.saveButton}><Text style={styles.buttonText}>{busy==='subject-save'?'Saving…':'Save subject'}</Text></Pressable></View>:<><View style={styles.headerRow}><Text style={styles.section}>Subject catalog · {subjects.length}</Text><Pressable accessibilityRole="button" onPress={newSubject} style={styles.newButton}><Text style={styles.newButtonText}>Add subject</Text></Pressable></View>{subjects.length?subjects.map(item=><View key={item._id} style={styles.card}><View style={styles.headerRow}><View style={styles.flex}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.caption}>{[item.courseCode,item.track,item.branch,item.semester?`Semester ${item.semester}`:null].filter(Boolean).join(' · ')}</Text></View><Pressable accessibilityRole="button" disabled={busy===item._id} onPress={()=>editSubject(item)}><Text style={styles.action}>{busy===item._id?'Loading…':'Edit'}</Text></Pressable><Pressable accessibilityRole="button" disabled={busy===item._id} onPress={()=>deleteSubject(item)}><Text style={styles.danger}>Delete</Text></Pressable></View></View>):<View style={styles.card}><Text style={styles.cardTitle}>No subjects found</Text><Text style={styles.muted}>Create the first subject for a university or competitive exam track.</Text></View>}</>}</>}
 {tab==='Review'&&<><Text style={styles.section}>Contribution review · {review.length}</Text>{review.length?review.map(item=><View key={item._id} style={styles.card}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.caption}>{item.subject?.name||'Subject'} · {item.unitTitle||'Unit'} · {item.contributor?.name||item.contributor?.email||'Contributor'}</Text>{item.description?<Text style={styles.muted}>{item.description}</Text>:null}{item.bounty?<Text style={styles.caption}>Bounty: {item.bounty.title} · {item.bounty.reward} credits</Text>:null}<View style={styles.actions}><Pressable accessibilityRole="button" disabled={busy===item._id} onPress={()=>reviewNote(item,'APPROVE')} style={styles.approve}><Text style={styles.buttonText}>Approve</Text></Pressable><Pressable accessibilityRole="button" disabled={busy===item._id} onPress={()=>reviewNote(item,'REJECT')} style={styles.reject}><Text style={styles.rejectText}>Reject</Text></Pressable></View></View>):<View style={styles.card}><Text style={styles.cardTitle}>Queue is clear</Text><Text style={styles.muted}>New campus contributions will appear here for review.</Text></View>}</>}
 {tab==='Reports'&&<><Text style={styles.section}>Broken link reports · {reports.length}</Text>{reports.length?reports.map(item=><View key={item._id} style={styles.card}><Text style={styles.cardTitle}>{item.resourceTitle}</Text><Text style={styles.caption}>{item.subject?.name||'Subject'} · {item.resourceType}{item.topic?` · ${item.topic}`:''}</Text><Text numberOfLines={2} style={styles.url}>{item.resourceUrl}</Text><View style={styles.actions}><Pressable disabled={busy===item._id} onPress={()=>resolveReport(item,'RESOLVED')} style={styles.approve}><Text style={styles.buttonText}>Resolve</Text></Pressable><Pressable disabled={busy===item._id} onPress={()=>resolveReport(item,'DISMISSED')} style={styles.reject}><Text style={styles.rejectText}>Dismiss</Text></Pressable></View></View>):<View style={styles.card}><Text style={styles.cardTitle}>No open reports</Text><Text style={styles.muted}>Broken-link reports submitted by students will appear here.</Text></View>}</>}
 </ScrollView></View>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#f7f8fc'},header:{paddingTop:20,paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:'#e7eaf1',backgroundColor:'#fff'},headerRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},flex:{flex:1},eyebrow:{color:'#315cf5',fontSize:9,fontWeight:'900',letterSpacing:1.1},title:{marginTop:4,color:'#101828',fontSize:23,fontWeight:'900'},logout:{color:'#9b1c1c',fontSize:11,fontWeight:'800'},tabs:{gap:6,paddingVertical:12},tab:{minHeight:35,justifyContent:'center',paddingHorizontal:12,borderRadius:9,backgroundColor:'#f2f4f8'},activeTab:{backgroundColor:'#eef3ff'},tabText:{color:'#687187',fontSize:11,fontWeight:'800'},activeTabText:{color:'#315cf5'},content:{padding:17,paddingBottom:34},section:{marginTop:5,marginBottom:10,color:'#101828',fontSize:17,fontWeight:'900'},stats:{flexDirection:'row',gap:8},stat:{flex:1,minHeight:80,justifyContent:'center',paddingHorizontal:10,borderWidth:1,borderColor:'#e7eaf1',borderRadius:13,backgroundColor:'#fff'},statValue:{color:'#101828',fontSize:20,fontWeight:'900'},statLabel:{marginTop:3,color:'#737b8c',fontSize:10,fontWeight:'700'},card:{marginTop:9,padding:14,borderWidth:1,borderColor:'#e7eaf1',borderRadius:14,backgroundColor:'#fff'},cardTitle:{color:'#101828',fontSize:13,fontWeight:'900'},caption:{marginTop:4,color:'#737b8c',fontSize:10,lineHeight:15},muted:{marginTop:9,color:'#687187',fontSize:12,lineHeight:18},action:{marginTop:9,color:'#315cf5',fontSize:11,fontWeight:'900'},input:{height:45,marginBottom:4,paddingHorizontal:12,borderWidth:1,borderColor:'#dfe4ed',borderRadius:11,color:'#101828',backgroundColor:'#fff'},jsonInput:{minHeight:320,maxHeight:600,marginTop:12,padding:12,borderWidth:1,borderColor:'#dfe4ed',borderRadius:11,color:'#20283a',backgroundColor:'#f7f8fc',fontFamily:'monospace',fontSize:11,lineHeight:16},newButton:{minHeight:36,justifyContent:'center',paddingHorizontal:10,borderRadius:9,backgroundColor:'#111318'},newButtonText:{color:'#fff',fontSize:10,fontWeight:'900'},saveButton:{alignSelf:'flex-start',minHeight:40,justifyContent:'center',marginTop:11,paddingHorizontal:14,borderRadius:10,backgroundColor:'#111318'},danger:{paddingVertical:8,color:'#9b1c1c',fontSize:10,fontWeight:'900'},actions:{flexDirection:'row',gap:8,marginTop:11},approve:{minHeight:38,justifyContent:'center',paddingHorizontal:13,borderRadius:9,backgroundColor:'#16794b'},buttonText:{color:'#fff',fontSize:10,fontWeight:'900'},reject:{minHeight:38,justifyContent:'center',paddingHorizontal:13,borderWidth:1,borderColor:'#eccaca',borderRadius:9,backgroundColor:'#fff7f7'},rejectText:{color:'#9b1c1c',fontSize:10,fontWeight:'900'},url:{marginTop:8,color:'#515b70',fontSize:10},errorCard:{marginBottom:10,padding:13,borderWidth:1,borderColor:'#f1c9c9',borderRadius:12,backgroundColor:'#fff7f7'},errorText:{color:'#9b1c1c',fontSize:11},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#f7f8fc'}});
