import React, {useCallback, useState} from 'react';
import {ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {useAuth} from '../context/AuthContext';
import {AcademiaUser} from '../context/AuthContext';
import {api, authApi, getApiErrorMessage} from '../services/api';
import {ProfileSetupEditor} from './ProfileSetupEditor';
import {ActivityHeatmap, ActivityDay} from '../components/ActivityHeatmap';

type Activity={days?:ActivityDay[];currentStreak?:number;longestStreak?:number;activeDays?:number};
export function ProfileScreen(): React.JSX.Element {
  const {user,logout,updateUser}=useAuth(); const [name,setName]=useState(user?.name||''); const [saving,setSaving]=useState(false); const [activity,setActivity]=useState<Activity|null>(null); const [loading,setLoading]=useState(true); const [activityError,setActivityError]=useState(''); const [editingSetup,setEditingSetup]=useState(false);
  useFocusEffect(useCallback(()=>{let active=true;api.get('/progress/activity').then(response=>{if(active){setActivity(response.data as Activity);setActivityError('');}}).catch(e=>{if(active)setActivityError(getApiErrorMessage(e,'Your career activity could not be loaded.'));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]));
  const saveName=async()=>{if(name.trim().length<2){Alert.alert('Check your name','Enter at least 2 characters.');return;}setSaving(true);try{const response=await authApi.updateProfile(profileUpdatePayload(user,{name:name.trim()}));const updated=(response.data as {user?:typeof user}).user;if(updated)updateUser(updated);Alert.alert('Profile saved','Your name has been updated.');}catch(e){Alert.alert('Could not save profile',getApiErrorMessage(e,'Try again.'));}finally{setSaving(false);}};
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>YOUR ACCOUNT</Text><Text style={styles.title}>Profile</Text>
    <View style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{(user?.name||'?').trim().charAt(0).toUpperCase()}</Text></View><Text style={styles.name}>{user?.name}</Text><Text style={styles.email}>{user?.email}</Text><Text style={styles.role}>{(user?.role||'STUDENT').toUpperCase()}</Text></View>
    <Text style={styles.section}>Academic profile</Text><View style={styles.card}><ProfileRow label="Study track" value={user?.track||'Not set'}/>{user?.track==='UNIVERSITY'?<><ProfileRow label="University" value={typeof user.tenant==='object'?user.tenant?.name||'Not set':user.tenant||'Not set'}/><ProfileRow label="Campus" value={user.college||'Not set'}/><ProfileRow label="Branch" value={user.branch||'Not set'}/><ProfileRow label="Year / semester" value={`${user.year||'—'} / ${user.semester||'—'}`}/></>:<><ProfileRow label="Target exam" value={user?.targetExam||'Not set'}/><ProfileRow label="Target year" value={String(user?.targetYear||'Not set')}/></>}<Pressable accessibilityRole="button" accessibilityState={{expanded:editingSetup}} onPress={()=>setEditingSetup(value=>!value)} style={styles.button}><Text style={styles.buttonText}>{editingSetup?'Close setup editor':'Change study setup'}</Text></Pressable></View>
    {editingSetup&&user&&<ProfileSetupEditor user={user} onCancel={()=>setEditingSetup(false)} onSaved={(updated:AcademiaUser)=>{updateUser(updated);setName(updated.name);setEditingSetup(false);}}/>}
    <Text style={styles.section}>Edit display name</Text><View style={styles.card}><TextInput accessibilityLabel="Display name" value={name} onChangeText={setName} maxLength={120} style={styles.input}/><Pressable accessibilityRole="button" disabled={saving} onPress={saveName} style={styles.button}><Text style={styles.buttonText}>{saving?'Saving…':'Save name'}</Text></Pressable></View>
    <Text style={styles.section}>Career practice activity</Text><View style={styles.card}><Text style={styles.streak}>{activity?.currentStreak||0} day streak</Text><Text style={styles.muted}>{activity?.activeDays||0} active days · longest streak {activity?.longestStreak||0} days</Text>{loading?<View style={styles.loading}><ActivityIndicator color="#315cf5"/><Text style={styles.muted}>Loading activity…</Text></View>:activityError?<Text accessibilityRole="alert" style={styles.error}>{activityError}</Text>:<><ActivityHeatmap days={activity?.days||[]}/><Text style={styles.caption}>Recent 12 months · each square represents a day of completed career practice</Text></>}</View>
    <Pressable accessibilityRole="button" onPress={()=>logout()} style={styles.logout}><Text style={styles.logoutText}>Sign out</Text></Pressable>
  </ScrollView>;
}
function ProfileRow({label,value}:{label:string;value:string}):React.JSX.Element{return <View style={styles.profileRow}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>;}
export function profileUpdatePayload(user: ReturnType<typeof useAuth>['user'], extra: Record<string, unknown>): Record<string, unknown> {
  if (!user) return extra;
  const payload: Record<string, unknown> = {track: user.track, ...extra};
  if (user.track === 'UNIVERSITY') {
    const tenantId = typeof user.tenant === 'object' ? user.tenant?._id || user.tenant?.id : user.tenant;
    return {...payload, tenantId, college: user.college, branch: user.branch, year: user.year, semester: user.semester};
  }
  return {...payload, targetExam: user.targetExam, targetYear: user.targetYear};
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#f7f8fc'},content:{padding:20,paddingBottom:38},eyebrow:{color:'#315cf5',fontSize:10,fontWeight:'900',letterSpacing:1.2},title:{marginTop:7,color:'#101828',fontSize:28,fontWeight:'900'},card:{marginTop:13,padding:16,borderWidth:1,borderColor:'#e7eaf1',borderRadius:16,backgroundColor:'#fff'},avatar:{width:54,height:54,alignItems:'center',justifyContent:'center',borderRadius:18,backgroundColor:'#eef3ff'},avatarText:{color:'#315cf5',fontSize:23,fontWeight:'900'},name:{marginTop:12,color:'#101828',fontSize:19,fontWeight:'900'},email:{marginTop:3,color:'#687187',fontSize:13},role:{alignSelf:'flex-start',marginTop:10,paddingHorizontal:9,paddingVertical:5,borderRadius:8,backgroundColor:'#f0f4ff',color:'#315cf5',fontSize:9,fontWeight:'900'},section:{marginTop:23,color:'#101828',fontSize:17,fontWeight:'900'},profileRow:{paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#f0f1f5'},rowLabel:{color:'#737b8c',fontSize:11,fontWeight:'700'},rowValue:{marginTop:3,color:'#101828',fontSize:13,fontWeight:'800'},input:{height:46,paddingHorizontal:12,borderWidth:1,borderColor:'#dfe4ed',borderRadius:11,color:'#101828'},button:{alignSelf:'flex-start',minHeight:42,justifyContent:'center',marginTop:11,paddingHorizontal:14,borderRadius:10,backgroundColor:'#111318'},buttonText:{color:'#fff',fontSize:12,fontWeight:'800'},streak:{color:'#101828',fontSize:16,fontWeight:'900'},muted:{marginTop:6,color:'#687187',fontSize:12,lineHeight:18},caption:{marginTop:10,color:'#737b8c',fontSize:10,lineHeight:15},loading:{alignItems:'center',paddingVertical:18},error:{marginTop:14,color:'#9b1c1c',fontSize:12},logout:{alignItems:'center',justifyContent:'center',minHeight:48,marginTop:18,borderWidth:1,borderColor:'#e7eaf1',borderRadius:12,backgroundColor:'#fff'},logoutText:{color:'#9b1c1c',fontSize:13,fontWeight:'900'}});
