import React, {useEffect, useMemo, useRef, useState} from 'react';
import {ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {AcademiaUser} from '../context/AuthContext';
import {getApiErrorMessage, subjectApi, tenantApi, authApi} from '../services/api';

type Track='UNIVERSITY'|'JEE'|'NEET';
type College={_id?:string;name:string};
type Tenant={_id:string;name:string;type:string;affiliatedColleges?:College[]};
type Props={user:AcademiaUser;onSaved:(user:AcademiaUser)=>void;onCancel:()=>void};
const thisYear=new Date().getFullYear();
export function ProfileSetupEditor({user,onSaved,onCancel}:Props):React.JSX.Element{
 const initialTenant=typeof user.tenant==='object'&&user.tenant?(user.tenant._id||user.tenant.id||''):typeof user.tenant==='string'?user.tenant:'';const initialBranch=useRef(user.branch||'');
 const[track,setTrack]=useState<Track>(user.track==='JEE'||user.track==='NEET'?user.track:'UNIVERSITY');const[tenants,setTenants]=useState<Tenant[]>([]);const[tenantId,setTenantId]=useState(initialTenant);const[campus,setCampus]=useState(user.college||'');const[branches,setBranches]=useState<string[]>([]);const[branch,setBranch]=useState(user.branch||'');const[year,setYear]=useState(user.year||1);const[semester,setSemester]=useState(user.semester||1);const[targetExam,setTargetExam]=useState(user.targetExam||'JEE_MAINS');const[targetYear,setTargetYear]=useState(user.targetYear||thisYear+1);const[loading,setLoading]=useState(true);const[branchLoading,setBranchLoading]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const tenant=tenants.find(item=>item._id===tenantId);const colleges=tenant?.affiliatedColleges||[];const semesters=useMemo(()=>[year*2-1,year*2],[year]);
 useEffect(()=>{let alive=true;tenantApi.getTenants().then(response=>{if(!alive)return;const list=((response.data as {tenants?:Tenant[]}).tenants||[]).filter(item=>item.type==='UNIVERSITY');setTenants(list);if(!initialTenant&&list[0]){setTenantId(list[0]._id);setCampus('');}}).catch(e=>{if(alive)setError(getApiErrorMessage(e,'Could not load universities.'))}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[initialTenant]);
 useEffect(()=>{let alive=true;if(track!=='UNIVERSITY'||!tenantId){setBranches([]);setBranch('');setBranchLoading(false);return()=>{alive=false}}setBranchLoading(true);subjectApi.getBranches(tenantId).then(response=>{if(!alive)return;const options=(response.data as {branches?:string[]}).branches||[];setBranches(options);const normalized=initialBranch.current.toUpperCase().replace(/[^A-Z0-9]/g,'');setBranch(options.find(value=>value.toUpperCase().replace(/[^A-Z0-9]/g,'')===normalized)||options[0]||'')}).catch(e=>{if(alive){setBranches([]);setError(getApiErrorMessage(e,'Could not load branches for this university.'))}}).finally(()=>{if(alive)setBranchLoading(false)});return()=>{alive=false}},[track,tenantId]);
 const save=async()=>{setError('');if(track==='UNIVERSITY'&&(!tenantId||!campus.trim()||!branch||branchLoading)){setError('Choose a university, campus, and branch before saving.');return}setSaving(true);try{const payload=track==='UNIVERSITY'?{track,tenantId,college:campus.trim(),branch,year,semester}:{track,targetExam:track==='NEET'?'NEET':targetExam,targetYear};const response=await authApi.updateProfile(payload);const updated=(response.data as {user?:AcademiaUser}).user;if(!updated)throw new Error('The server did not return your updated profile.');onSaved(updated)}catch(e){setError(getApiErrorMessage(e,'Could not update your academic profile.'))}finally{setSaving(false)}};
 if(loading)return <View style={styles.loading}><ActivityIndicator color="#315cf5"/><Text style={styles.help}>Loading profile options…</Text></View>;
 return <View style={styles.container}><View style={styles.headingRow}><View style={styles.flex}><Text style={styles.title}>Update your study setup</Text><Text style={styles.help}>Your selection controls the subjects and tools shown in the app.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close profile editor" onPress={onCancel} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>
  <ScrollView style={styles.form} contentContainerStyle={styles.formContent} keyboardShouldPersistTaps="handled"><Text style={styles.label}>LEARNING TRACK</Text><View style={styles.options}>{(['UNIVERSITY','JEE','NEET'] as Track[]).map(value=><Chip key={value} text={value==='UNIVERSITY'?'University':value} active={track===value} onPress={()=>{setTrack(value);if(value==='NEET')setTargetExam('NEET');else if(targetExam==='NEET')setTargetExam('JEE_MAINS');setError('')}}/>)}</View>
  {track==='UNIVERSITY'?<><Text style={styles.label}>UNIVERSITY</Text>{tenants.length?<View style={styles.options}>{tenants.map(item=><Chip key={item._id} text={item.name} active={tenantId===item._id} onPress={()=>{setTenantId(item._id);setCampus('');setBranch('')}}/>)}</View>:<Text style={styles.help}>No active universities are available.</Text>}
   {!!tenant&&<><Text style={styles.label}>COLLEGE / CAMPUS</Text>{colleges.length>0&&<View style={styles.options}>{colleges.map(item=><Chip key={item._id||item.name} text={item.name} active={campus===item.name} onPress={()=>setCampus(item.name)}/>)}</View>}<TextInput accessibilityLabel="College or campus name" value={campus} onChangeText={setCampus} placeholder="Enter your college or campus" style={styles.input}/>
   <Text style={styles.label}>BRANCH{branchLoading?' · LOADING':''}</Text>{branches.length?<View style={styles.options}>{branches.map(value=><Chip key={value} text={value} active={branch===value} onPress={()=>setBranch(value)}/>)}</View>:<Text style={styles.help}>{branchLoading?'Loading branches…':'No branches are configured for this university.'}</Text>}
   <Text style={styles.label}>YEAR</Text><View style={styles.options}>{[1,2,3,4].map(value=><Chip key={value} text={`Year ${value}`} active={year===value} onPress={()=>{setYear(value);setSemester(value*2-1)}}/>)}</View><Text style={styles.label}>SEMESTER</Text><View style={styles.options}>{semesters.map(value=><Chip key={value} text={`Semester ${value}`} active={semester===value} onPress={()=>setSemester(value)}/>)}</View></>}
  </>:<>{track==='JEE'&&<><Text style={styles.label}>TARGET EXAM</Text><View style={styles.options}>{[['JEE_MAINS','JEE Main'],['JEE_ADVANCED','JEE Advanced']].map(([value,label])=><Chip key={value} text={label} active={targetExam===value} onPress={()=>setTargetExam(value)}/>)}</View></>}<Text style={styles.label}>TARGET YEAR</Text><View style={styles.options}>{[thisYear,thisYear+1,thisYear+2,thisYear+3].map(value=><Chip key={value} text={String(value)} active={targetYear===value} onPress={()=>setTargetYear(value)}/>)}</View></>}
  {!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<View style={styles.actions}><Pressable accessibilityRole="button" disabled={saving} onPress={onCancel} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable accessibilityRole="button" disabled={saving||branchLoading} onPress={save} style={styles.save}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.saveText}>Save setup</Text>}</Pressable></View>
  </ScrollView>
 </View>;
}
function Chip({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}):React.JSX.Element{return <Pressable accessibilityRole="radio" accessibilityState={{selected:active}} onPress={onPress} style={[styles.chip,active&&styles.chipActive]}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{text}</Text></Pressable>}
const styles=StyleSheet.create({container:{marginTop:16,padding:15,borderWidth:1,borderColor:'#dce2ef',borderRadius:16,backgroundColor:'#fff'},headingRow:{flexDirection:'row',alignItems:'flex-start',gap:8},flex:{flex:1},title:{color:'#101828',fontSize:17,fontWeight:'900'},help:{marginTop:4,color:'#687187',fontSize:11,lineHeight:17},close:{width:36,height:36,alignItems:'center',justifyContent:'center',borderRadius:10,backgroundColor:'#f2f4f8'},closeText:{color:'#687187',fontSize:23,lineHeight:25},form:{maxHeight:430,marginTop:8},formContent:{paddingBottom:5},label:{marginTop:16,marginBottom:7,color:'#737b8c',fontSize:9,fontWeight:'900',letterSpacing:.6},options:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{minHeight:36,justifyContent:'center',paddingHorizontal:11,borderWidth:1,borderColor:'#e1e5ed',borderRadius:10,backgroundColor:'#fff'},chipActive:{borderColor:'#315cf5',backgroundColor:'#eef3ff'},chipText:{color:'#687187',fontSize:10,fontWeight:'800'},chipTextActive:{color:'#315cf5'},input:{height:43,marginTop:8,paddingHorizontal:11,borderWidth:1,borderColor:'#dfe4ed',borderRadius:10,color:'#101828',fontSize:12},actions:{flexDirection:'row',justifyContent:'flex-end',gap:8,marginTop:18},cancel:{minHeight:42,justifyContent:'center',paddingHorizontal:14,borderWidth:1,borderColor:'#e1e5ed',borderRadius:10},cancelText:{color:'#687187',fontSize:11,fontWeight:'800'},save:{minWidth:112,minHeight:42,alignItems:'center',justifyContent:'center',paddingHorizontal:13,borderRadius:10,backgroundColor:'#111318'},saveText:{color:'#fff',fontSize:11,fontWeight:'800'},error:{marginTop:12,color:'#9b1c1c',fontSize:11,lineHeight:16},loading:{alignItems:'center',padding:18}});
