import React, {useCallback, useState} from 'react';
import {ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {api, getApiErrorMessage} from '../services/api';
import {useAuth} from '../context/AuthContext';
import {profileUpdatePayload} from './ProfileScreen';

type Ranking = {success?: boolean; available?: boolean; participating?: boolean; message?: string; cohortSize?: number; yourRank?: number | null; yourReadiness?: number | null; topTenPercent?: boolean; cohort?: {college?: string; branch?: string; semester?: number}; topTen?: Array<{rank: number; label: string; averageReadiness: number}>};
export function RankingsScreen(): React.JSX.Element {
  const {user}=useAuth();
  const [data,setData]=useState<Ranking|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const load=useCallback(async(background=false)=>{background?setRefreshing(true):setLoading(true);setError('');try{const response=await api.get('/progress/leaderboard');setData(response.data as Ranking);}catch(e){setError(getApiErrorMessage(e,'Could not load cohort rankings.'));}finally{setLoading(false);setRefreshing(false);}},[]);
  useFocusEffect(useCallback(()=>{load(true).catch(()=>{});},[load]));
  const setOptIn=async()=>{if(!data)return;setSaving(true);try{await api.put('/auth/profile',profileUpdatePayload(user,{leaderboardOptIn:!data.participating}));await load(true);}catch(e){setError(getApiErrorMessage(e,'Could not update leaderboard privacy.'));}finally{setSaving(false);}};
  if(loading)return <View style={styles.center} accessibilityRole="progressbar"><ActivityIndicator size="large" color="#315cf5"/><Text style={styles.muted}>Loading your cohort…</Text></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor="#315cf5"/>}><Text style={styles.eyebrow}>LEARN TOGETHER</Text><Text style={styles.title}>Rankings</Text><Text style={styles.muted}>Private cohort rankings use syllabus readiness. Your name and email are never shown.</Text>
    {error?<View style={styles.card}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>load()}><Text style={styles.link}>Try again</Text></Pressable></View>:null}
    {data?.available? <><View style={styles.highlight}><Text style={styles.highlightLabel}>YOUR COHORT POSITION</Text><Text style={styles.rank}>{data.yourRank?`#${data.yourRank}`:'Not ranked'}</Text><Text style={styles.highlightMeta}>{data.yourReadiness ?? 0}% readiness · {data.cohortSize} opted-in students</Text>{data.cohort&&<Text style={styles.highlightMeta}>{data.cohort.college} · {data.cohort.branch} · Semester {data.cohort.semester}</Text>}{data.topTenPercent&&<Text style={styles.badge}>Top 10% of your cohort</Text>}</View><Text style={styles.section}>Top performers</Text>{data.topTen?.map((row,index)=><View key={`${row.rank}-${index}`} style={styles.card}><Text style={styles.peer}>{row.label}</Text><Text style={styles.score}>{row.averageReadiness}%</Text></View>)}</>:<View style={styles.card}><Text style={styles.cardTitle}>Rankings are not available yet</Text><Text style={styles.muted}>{data?.message||'Complete your academic profile and opt in to join your campus cohort.'}</Text></View>}
    <View style={styles.privacy}><Text style={styles.cardTitle}>Leaderboard privacy</Text><Text style={styles.muted}>Participation is optional. Peers see anonymous labels and readiness scores only.</Text><Pressable accessibilityRole="switch" accessibilityState={{checked:!!data?.participating,disabled:saving}} disabled={saving} onPress={setOptIn} style={styles.button}><Text style={styles.buttonText}>{saving?'Saving…':data?.participating?'Leave rankings':'Join rankings'}</Text></Pressable></View>
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#f7f8fc'},content:{padding:20,paddingBottom:36},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#f7f8fc'},eyebrow:{color:'#315cf5',fontSize:10,fontWeight:'900',letterSpacing:1.2},title:{marginTop:7,color:'#101828',fontSize:28,fontWeight:'900'},muted:{marginTop:6,color:'#687187',fontSize:13,lineHeight:20},highlight:{marginTop:18,padding:18,borderRadius:18,backgroundColor:'#111318'},highlightLabel:{color:'#aebbe7',fontSize:10,fontWeight:'900',letterSpacing:1},rank:{marginTop:7,color:'#fff',fontSize:36,fontWeight:'900'},highlightMeta:{marginTop:6,color:'#d9deea',fontSize:12},badge:{alignSelf:'flex-start',marginTop:12,paddingHorizontal:10,paddingVertical:6,borderRadius:9,backgroundColor:'#315cf5',color:'#fff',fontWeight:'800'},section:{marginTop:24,color:'#101828',fontSize:18,fontWeight:'900'},card:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:10,padding:16,borderWidth:1,borderColor:'#e7eaf1',borderRadius:15,backgroundColor:'#fff'},cardTitle:{color:'#101828',fontSize:15,fontWeight:'900'},peer:{color:'#101828',fontSize:14,fontWeight:'800'},score:{color:'#315cf5',fontSize:15,fontWeight:'900'},privacy:{marginTop:24,padding:16,borderWidth:1,borderColor:'#e7eaf1',borderRadius:16,backgroundColor:'#fff'},button:{alignSelf:'flex-start',minHeight:42,justifyContent:'center',marginTop:13,paddingHorizontal:14,borderRadius:10,backgroundColor:'#111318'},buttonText:{color:'#fff',fontSize:12,fontWeight:'800'},error:{color:'#9b1c1c',fontSize:13},link:{marginTop:8,color:'#315cf5',fontWeight:'800'}});
